### PR TITLE
More detail in instructions for running Cockpit

### PR DESCRIPTION
**Pull request by mihbor**

### CODE REVIEW

**Comment by berndruecker** [comment]
Thanks for the PR! Why do you stated that no password is required? The standard distributions do use the password "sa" for user "sa".

**Comment by mihbor** [comment]
I ran flowing-retail first, then tried to run cockpit from the standard distribution and have it connect to the h2 used by flowing-retail. Cockpit didn't work for me with the password but worked without. I assumed flowing-retail had set a different (blank) password for its in-memory h2 instance than the standard distribution uses.

**Comment by berndruecker** [comment]
Ah sorry - now I got it. you are right - in the flowing-retail there is no password set. It might be easier to adjust it there to avoid confusion - I will double check

**Comment by mihbor** [comment]
Cheers :-)

**Comment by berndruecker** [comment]
I changed the codebase to also use sa/sa when starting the flowing retail, then the distro doesn't have to be touched for this. I liked it more this way round. Thanks a lot for raising the issue!

**Comment by mihbor** [comment]
Makes sense, thank you.

**Pull request merged**
